version: "3.9"

services:
  analytics-postgres:
    image: postgres:15
    container_name: analytics-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - analytics_pgdata:/var/lib/postgresql/data
    networks:
      - astro-etl_a9b3bd_airflow
    restart: unless-stopped

volumes:
  analytics_pgdata:

networks:
  astro-etl_a9b3bd_airflow:
    external: true
